name = "pcp-contact"
main = "src/index.ts"
compatibility_date = "2026-04-24"
workers_dev = true

routes = [
  { pattern = "www.rapiddirect.com/api/contact*", zone_name = "rapiddirect.com" },
]0

[vars]
ALLOWED_ORIGIN = "https://www.rapiddirect.com"
FROM_EMAIL = "quote@rapiddirect.com"
TO_EMAIL = "pcb@rapiddirect.com"
